#!/bin/bash

./build -Lp wsdd
./build -Lp speedtest-cli
./build -Lp -t jammy -a UBUNTU_IMAGE_VERSION=jammy ubuntu-build-essential
./build -Lp minidlna

LATEST_SAMBA=$(docker run --rm alpine /bin/sh -c "apk update 2>&1 >/dev/null; apk search -x samba 2>/dev/null | sed 's#samba\-##g'")
if [[ "$LATEST_SAMBA" != "" ]]; then
    ./build -Lp -t "${LATEST_SAMBA}" samba
else
    ./build -Lp samba
fi
unset LATEST_SAMBA

./build -Lp -P linux/amd64,linux/arm64 minecraft-server

./build -p -t "15.0.0" -a ANGULAR_VER=@^15.0.0 angular-devcontainer
